# Deploy on RHEL/CentOS/Rocky/Alma/OracleLinux systems

- name: "[RHEL] Check .rpm exists locally"
  ansible.builtin.stat:
    path: "{{ vmtools_pkg_file }}"
  delegate_to: localhost
  become: false
  register: rpm_file
  failed_when: not rpm_file.stat.exists

- name: "[RHEL] Copy .rpm to target"
  ansible.builtin.copy:
    src: "{{ vmtools_pkg_file }}"
    dest: "/tmp/{{ vmtools_pkg_file | basename }}"
    mode: '0644'

- name: "[OL8] Check ol8_codeready_builder repo status"
  ansible.builtin.command:
    cmd: dnf repolist enabled
  register: _ol8_repolist
  changed_when: false
  when:
    - ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version == "8"

- name: "[OL8] Enable ol8_codeready_builder if not enabled"
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled ol8_codeready_builder
  when:
    - ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version == "8"
    - "'ol8_codeready_builder' not in _ol8_repolist.stdout"
  failed_when: false

- name: "[RHEL] Remove standard open-vm-tools"
  ansible.builtin.command:
    cmd: dnf remove -y open-vm-tools open-vm-tools-desktop
  when:
    - vmtools_remove_standard | bool
    - has_standard_tools | bool
  failed_when: false
  changed_when: true

- name: "[RHEL] Stop running vmtoolsd services"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop:
    - vmtoolsd
    - open-vm-tools
  failed_when: false

- name: "[RHEL] Install custom .rpm"
  ansible.builtin.command:
    cmd: "dnf install -y --nogpgcheck /tmp/{{ vmtools_pkg_file | basename }}"
  changed_when: true
