# =============================================================================
# Inventory VMware Tools Deployment
# =============================================================================
#
# Aggiungi le tue macchine nei gruppi corretti.
#

[debian]
# crd-haproxy01 ansible_host=10.0.0.1
# crd-haproxy02 ansible_host=10.0.0.2
# zabbixproxy-new ansible_host=10.0.0.3

[rhel]
# crd-app01 ansible_host=10.0.0.10
# crd-app02 ansible_host=10.0.0.11

[all:vars]
ansible_user=root
